mass: 20

Ixx: 0.1473
Iyy: 0.3917
Izz: 0.3777
Ixy: 0.0
Ixz: 0.0
Iyz: 0.0

left_abad_location: [-0.048, 0.173, 0]
left_hip_location: [-0.188, 0.213, 0]
leg_length: [0.04, 0.14, 0.512, 0.49] # hip_ext, l1, l2, l3

sphere_joint_location: [0.216, 0, 0.09]
# ext_wrench: [0, 0, 0, 0, 0, 5]
ext_wrench: [0, 0, 0, 5, 0, 12]