# control frequency
control_dt: 0.001

# gait
gait_resolution: 120  # divide gait phase into # portions

# MPC info
nIterationsPerMPC: 50
mpc_horizon: 10
q_weights: [50.0, 70.0, 1000.0,    # Roll Pitch Yaw
            10.0, 10.0, 100.0,    # Posx Posy Posz
            5.0, 20.0, 50.0,    # corresponding derivative
            10.0, 10.0, 50.0 ]

# q_weights: [20.0, 50.0, 100.0,    # Roll Pitch Yaw
#             0.0, 0.0, 60.0,    # Posx Posy Posz
#             6.0, 10.0, 10.0,    # corresponding derivative
#             0.0, 0.0, 50.0 ]



r_weights: [0.5, 0.5, .5,
            0.5, 0.5, .5] # fx fy fz

mu: 0.3


# Swing foot(left)
default_foot_pos_under_hip: [-0.04, -0.025, -0.9]

# kinematics
max_iter: 100
ik_eps: 0.005